# Generated by Django 6.0.7 on 2026-09-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message_type',
            field=models.CharField(choices=[('problema', 'Reportar un problema'), ('sugerencia', 'Sugerencia para la app'), ('otra', 'Otra consulta o solicitud')], max_length=20, verbose_name='tipo de mensaje'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='resuelto'),
        ),
    ]
